### ISSUE TITLE
[SF3] Crash using Terrain Scanner

### ISSUE THREAD

**Issue by omghdf** [Eladkay/Scanner#7] opened 2017-01-08 23:24 UTC
It happend a few times now. It worked stable for at first.
I set up Terrain Scanner but in the wrong Chunk (already build). So disconnected the power and opened up the Interface to hit the stop button -> Crash
[crash-2017-01-08_23.43.52-client.txt](https://github.com/Eladkay/Scanner/files/692505/crash-2017-01-08_23.43.52-client.txt)
Updated BrandonsCore + CodeChickenAPI: Tried opening the Interface again -> Crash
[crash-2017-01-09_00.21.14-client.txt](https://github.com/Eladkay/Scanner/files/692522/crash-2017-01-09_00.21.14-client.txt)

**Comment by Eladkay** [comment] 2017-01-09 19:34
I'll fix it i think

**Comment by omghdf** [comment] 2017-01-10 00:57
Awesome. I realy like this mod and would love to use it more.

**Comment by Eladkay** [comment] 2017-01-13 10:44
3e49741

**Comment by itanshi** [comment] 2017-01-15 19:46
[crash-2017-01-14_13.17.56-client.txt](https://github.com/Eladkay/Scanner/files/706840/crash-2017-01-14_13.17.56-client.txt)

might be same thing, not sure.

**Comment by Eladkay** [comment] 2017-01-15 19:52
Seems like it, darn it. Resolution? GUI Scale? Any graphical info will help

**Comment by Eladkay** [comment] 2017-01-17 13:28
Anyone? @omghdf

**Comment by DingoX3** [comment] 2017-01-24 00:44
Im having the same crash when trying to use the scanner while its running or if i place the biome block and try to look at the map. Full Crash report: http://pastebin.com/nwPsnmwy   In game video settings: GUI scale Large. Graphics Fancy. Smooth lighting Maximum. Brightness Bright. Particles All. Use Vsync off. Use VBOs On. Render distance 8. Max framerate Unlimited. Clouds Off. Fullscreen Off. Mipmap Levels off. Entity shadows On. 3d anaglyph Off. Hope some of this info helps. Great mod. Good idea for skyblock.

**Comment by Eladkay** [comment] 2017-01-24 12:18
Please show setup. Try without using Ender IO conduits at all

**Comment by Eladkay** [comment] 2017-01-28 11:58
Trying to figure this out:
The line referenced in GuiContainer is `this.returningStack = null;` which is in drawScreen.
This line cannot get an NPE in java in any case. One possibility is a core mod messing it up which makes sense considering this isn't reproducible by itself, I'll talk about that in a bit.
The line referenced in GuiTerrainScanner is `super.drawScreen(mouseX, mouseY, partialTicks);` which obviously makes sense.
Scanner builds on Forge 12.18.3.2185 with MCP stable_29. SkyFactory 3 version 3.0.4 runs on Forge 12.18.3.2202. I'll try changing to that build even though I have doubts that will make a difference.

Core mods:

>   ForgelinPlugin (Forgelin-1.2.0.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.1.104-universal.jar)
  llibrary (llibrary-1.7.2-1.10.2.jar)
  SurgeLoadingPlugin (Surge-1.10.2-1.1.0.66.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.64-beta.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.4r.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.1-anarchy.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.199-universal.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
  literalascension (literalascension-1.10.2-1.0.0.3.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)

Now let's iron out the ones that I know for sure don't mess it up:


>   LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
>   LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
>   BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
>   SurgeLoadingPlugin (Surge-1.10.2-1.1.0.66.jar)
>   EnderCorePlugin (EnderCore-1.10.2-0.4.1.64-beta.jar)
>   CCLCorePlugin (CodeChickenLib-1.10.2-2.5.2.198-universal.jar)
>   ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)


My personal suspect is ResourceLoader but considering that is dependent on more files and considering that to this point I was unable to reproduce this crash myself, this will be tough to test. I will forward this
to potentially responsible mod authors. In the meanwhile, let's see if changing the Forge version made any difference:
`this.returningStack = null;`
Nope. So it's definitely a coremod. Let's look at ResourceLoader's code:
`private byte[] patchMinecraft(byte[] basicClass)` 
Skip a few lines...
```
if (mn.name.equals(MCPNames.method("func_110436_a"))) {
        refreshResources = mn;
      } else if (mn.name.equals(MCPNames.method("func_71384_a"))) {
        startGame = mn;
      }
```
That's probably not the problem..
I'm clueless. This is my entire thought process when trying to fix this weird bug. Can someone slightly more knowledgeable than me take a look and see exactly why is this happening?

**Comment by covers1624** [comment] 2017-01-28 13:33
Attempt to reproduce the Issue with NEI uninstalled.

**Comment by Eladkay** [comment] 2017-01-28 15:42
^ @itanshi @omghdf @DingoX3

**Comment by Curse187** [comment] 2017-03-06 17:45
Same issues here. see report of crash. 
[crash-2017-03-06_17.54.48-client.txt](https://github.com/Eladkay/Scanner/files/821978/crash-2017-03-06_17.54.48-client.txt)

Workaround for me: i have to wait its finished complete with one chunk

**Comment by BonaireDreams** [comment] 2017-03-24 17:40
SF3 3.0.6 Terrain scanner worked fine. 3.0.8 crashes when clicking map button. Unable to even select a chunk to start the machine. Just found this thread while reading at work. I'll upload logs tonight.

**Comment by BonaireDreams** [comment] 2017-03-24 23:07
Removed resource packs and still crashes as soon as you hit map. Also tried moving 1.4.jar and config to 3.0.8 which just caused massive lag loading in. I was able to get to gui and hit map, also crashed. Put 1.4.1 back in.

[crash-2017-03-24_16.05.05-client.txt](https://github.com/Eladkay/Scanner/files/869409/crash-2017-03-24_16.05.05-client.txt)

Running  Win 10 with latest Geforce 378.92 driver

Biome Scanner does the same, except of course it crashes as soon as you right click. So its definatly something to do with the map rendering.

**Comment by MxtressMyxx** [comment] 2017-03-27 17:42
I am also currently experiencing this crash on SF 3.0.8 - this was not an issue in 3.0.6

**Comment by Eladkay** [comment] 2017-03-27 19:06
Try updating to latest.

**Comment by MxtressMyxx** [comment] 2017-03-27 20:01
I did. Server is 3.0.8 as well as client.

Edit: Updated client plugin from 1.4.1 to 1.5 and it is working, no action needed server side.

**Comment by Eladkay** [comment] 2017-03-28 10:04
This is a bug caused by FTBU which I fixed in the new version. I told darkosto to update it.

**Comment by BonaireDreams** [comment] 2017-03-30 01:52
Can confirm issue is fixed in the new version of scanners. Works for SF3.0.8. But still no trees :( I do get enderlilys when generating terrain in the end but no trees in the overworld. :(

**Comment by Eladkay** [comment] 2017-03-30 05:32
This is a separate issue.

**Closed as completed by Eladkay** 2017-03-30 05:32 UTC
